default_context:
    name: "Eva Maxfield Brown"
    email: "evamaxfieldbrown@gmail.com"
    github_username: "evamaxfield"
    project_name: "Swagit Dataset Generator"
    project_slug: "swagit-dataset-generator"
    python_slug: "swagit_dataset_generator"
    project_short_description: "A small package to generate a dataset of municipal council meeting metadata from Swagit."
    pypi_username: "evamaxfield"
    version: "0.0.0"
    license: "MIT License"