name: Check Pull Request

on: pull_request

# Cancel actions when new commits are pushed to PR
concurrency: 
    group: ${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: extractions/setup-just@v1
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[ci]
    - name: Run tests with Tox
      run: tox -e py
    - name: Upload Codecov
      uses: codecov/codecov-action@v1

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: extractions/setup-just@v1
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[ci]
    - name: Lint
      run: just lint

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - uses: extractions/setup-just@v1
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install .[docs]
    - name: Generate Docs
      run: |
        just generate-docs
